connections:
    database:
        host: 123.45.67.89
        username: username
        password: password
        dbname: databasename
        port: 3306
    memcache:
        host: 123.56.89.00
        port: 12345

apikeys:
    google_geocoding: xxxxxxxx
    askgeo:
        accountid: 1234
        key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        format: obj # (obj, json or xml)
        secure: true # (true=https, false=http)
