connections:
    database:
        host: mysql
        username: dev
        password: dev
        dbname: database
        port: 3306
    memcache:
        host: memcached
        port: 11211

apikeys:
    google_geocoding: xxxxxxxx
    askgeo:
        accountid: 1234
        key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        format: obj # (obj, json or xml)
        secure: true # (true=https, false=http)
